on:
  push:
    branches:    
      - master
      
name: Build and Publish Averment
jobs:
  SFTP-Deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: FTP-Deploy-Action
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        ssh_private_key: ${{ secrets.FTP_SSH_KEY }}
        remote_path: /public_html/
        
